Repository lilauu/COMP3404-ASE, pull requests merged in 2025-04, with the labels that each got.

#33 settings page
  COMP3404/COMP3404-Client/AppShell.xaml
  COMP3404/COMP3404-Client/COMP3404-Client.csproj
  COMP3404/COMP3404-Client/HistoryPage.xaml
  COMP3404/COMP3404-Client/HistoryPage.xaml.cs
  COMP3404/COMP3404-Client/MainPage.xaml
  COMP3404/COMP3404-Client/MainPage.xaml.cs
  COMP3404/COMP3404-Client/SettingsPage.xaml
  COMP3404/COMP3404-Client/SettingsPage.xaml.cs
Labels: Requirement - Personalization

#36 Login flow
  .gitignore
  COMP3404/COMP3404-Client/App.xaml.cs
  COMP3404/COMP3404-Client/COMP3404-Client.csproj
  COMP3404/COMP3404-Client/MainPage.xaml.cs
  COMP3404/COMP3404-Client/MauiProgram.cs
  COMP3404/COMP3404-Client/Platforms/Android/AndroidManifest.xml
  COMP3404/COMP3404-Client/Platforms/Android/WebAuthenticationCallbackActivity.cs
  COMP3404/COMP3404-Client/Platforms/Windows/App.xaml.cs
  COMP3404/COMP3404-Client/Platforms/Windows/Package.appxmanifest
  COMP3404/COMP3404-Client/SettingsPage.xaml.cs
  COMP3404/COMP3404-Server.Tests/COMP3404-Server.Tests.csproj
  COMP3404/COMP3404-Server.Tests/Controllers/AccountControllerTest.cs
  COMP3404/COMP3404-Server/COMP3404-Server.csproj
  COMP3404/COMP3404-Server/COMP3404-Server.http
  COMP3404/COMP3404-Server/Controllers/AccountController.cs
  COMP3404/COMP3404-Server/Controllers/WeatherForecastController.cs
  COMP3404/COMP3404-Server/Database/DatabaseContext.cs
  COMP3404/COMP3404-Server/Program.cs
  COMP3404/COMP3404-Server/Repositories/IUserAccountRepository.cs
  COMP3404/COMP3404-Server/Repositories/Repository.cs
  COMP3404/COMP3404-Server/Startup.cs
  COMP3404/COMP3404-Server/WeatherForecast.cs
  COMP3404/COMP3404-Server/appsettings.Development.json
  COMP3404/COMP3404-Server/appsettings.json
  COMP3404/COMP3404-Shared/Account.cs
  COMP3404/COMP3404-Shared/Models/Accounts/UserAccount.cs
  COMP3404/COMP3404-Shared/Models/Api/Github/GetUserResponse.cs
  COMP3404/COMP3404-Shared/Models/Api/GithubOAuthResponse.cs
  COMP3404/COMP3404.slnLaunch
Labels: Requirement - User Registration and Login

#38 Create stub AI implementation
  COMP3404/COMP3404-Client/AI/IAIModel.cs
  COMP3404/COMP3404-Client/AI/Stub/StubAIModel.cs
  COMP3404/COMP3404-Client/COMP3404-Client.csproj
  COMP3404/COMP3404-Shared/Models/Chats/ChatInteraction.cs
  COMP3404/COMP3404-Shared/Models/Chats/Conversation.cs
Labels: Requirement - AI Integration

#42 Create a reusable View for a Message
  COMP3404/COMP3404-Client/COMP3404-Client.csproj
  COMP3404/COMP3404-Client/MainPage.xaml
  COMP3404/COMP3404-Client/MainPage.xaml.cs
  COMP3404/COMP3404-Client/ViewModels/MainPageViewModel.cs
  COMP3404/COMP3404-Client/ViewModels/MessageViewModel.cs
  COMP3404/COMP3404-Client/Views/MessageView.xaml
  COMP3404/COMP3404-Client/Views/MessageView.xaml.cs
Labels: Requirement - Usability

#43 Refactor a lot of UI and theme stuff
  COMP3404/COMP3404-Client/COMP3404-Client.csproj
  COMP3404/COMP3404-Client/HistoryPage.xaml
  COMP3404/COMP3404-Client/HistoryPage.xaml.cs
  COMP3404/COMP3404-Client/MainPage.xaml
  COMP3404/COMP3404-Client/MainPage.xaml.cs
  COMP3404/COMP3404-Client/Resources/Styles/Colors.xaml
  COMP3404/COMP3404-Client/Resources/Styles/Styles.xaml
  COMP3404/COMP3404-Client/SettingsPage.xaml
  COMP3404/COMP3404-Client/SettingsPage.xaml.cs
  COMP3404/COMP3404-Client/Themes/DarkTheme.xaml
  COMP3404/COMP3404-Client/Themes/DarkTheme.xaml.cs
  COMP3404/COMP3404-Client/Themes/LightTheme.xaml
  COMP3404/COMP3404-Client/Themes/LightTheme.xaml.cs
  COMP3404/COMP3404-Client/Views/HeaderView.xaml
  COMP3404/COMP3404-Client/Views/HeaderView.xaml.cs
  COMP3404/COMP3404-Client/Views/MessageView.xaml
  COMP3404/COMP3404-Client/Views/NavbarView.xaml
  COMP3404/COMP3404-Client/Views/NavbarView.xaml.cs
Labels: Requirement - Usability
